name: data
channels:
  - anaconda
  - plotly
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - scipy=1.4
  - scikit-learn=0.22
  - plotly=4.5
  - seaborn=0.10
  - statsmodels=0.11
  - scikit-learn=0.22
  - ipykernel=5.1
  - jupyter=1.0
  - jupyterlab-plotly-extension=1.0

# pip install scikit-posthocs
